package com.smartshop.enums;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    LOGOUT,
    CREATE_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    RESTORE_PRODUCT,
    CREATE_CATEGORY,
    UPDATE_CATEGORY,
    CREATE_PURCHASE,
    RECORD_SUPPLIER_PAYMENT,
    CREATE_SUPPLIER,
    UPDATE_SUPPLIER,
    CREATE_SALE,
    CANCEL_SALE,
    CREATE_EXPENSE,
    DELETE_EXPENSE,
    UPDATE_SETTINGS,
    CREATE_USER,
    UPDATE_USER_STATUS,
    RESET_PASSWORD
}
